
export const ROUTES = {
  LANDING: '/landing',
  INDEX: '/',
  SIGNUP: '/signup',
  SIGNIN: '/signin',
  FORGOT_PASSWORD: '/forgot-password',
  CHANGE_PASSWORD: '/change-password',
  DASHBOARD: '/dashboard',
  ALL_CAROUSELS: '/all-carousels',
  PERSONA_MANAGEMENT: '/personas-management',
  ANALYTICS_DASHBOARD: '/analytics-dashboard',
  ACCOUNT: '/account',
  ACCOUNT_PERSONAL: '/account/personal',
  ACCOUNT_BILLING: '/account/billing',
  ACCOUNT_PREFERENCE: '/account/preference',
  ACCOUNT_LINKEDIN: '/account/linkedin',
  ACCOUNT_PASSWORD: '/account/password',
  ACCOUNT_LOGOUT: '/account/logout',
  ACCOUNT_SETTINGS: '/account',
  PRICING_PLAN: '/pricing-plan',
  CAROUSEL_EDITOR: '/carousel-editor',
  CAROUSEL_EDITOR_SCRATCH: '/carousel-editor/scratch',
  CAROUSEL_EDITOR_IDEA_GENERATOR: '/carousel-editor/idea-generator',
  CAROUSEL_EDITOR_PREVIEW: '/carousel-editor/preview',
  CONTACT_US: '/contact-us',
};
